#' @title Additional relationship check between variables
#' @name tableTwo
#' @description This function applies different regression model based the type of response variable
#' to do additional relationship check.
#' @usage tableTwo(formula, table, Multi=TRUE, CI=TRUE, poisson=FALSE)
#' @param formula an object of class "formula" (y ~ x1 + x2 + x3):
#'                a symbolic description of the model to be fitted.
#' @param table a dataframe generated by showInfo function in this package.
#' @param Multi option to apply univariate analysis or multivariable analysis.
#' @param CI option to show confidence interval in the table.
#' @param poisson option to apply poisson regression.
#' @details This function test applies a regression model based the response variable.
#' If the response variable in the formula is categorial with two levels, then it will apply
#' binomial logit function. User can choose to apply multivariate or univariate test. As the
#' result, this function will return a table and a odds plot. If the response variable has
#' more than 2 levels, then this function will stop and tell user, we cannot deal with it.
#' When the function detects the response variable is continuous, it will apply Wilcox test,
#' T-Test, ANOVA test and linear regression. And user also can choose to apply poisson
#' regression by parameter poisson.
#' @return a univariate or multivariable data frame
#' @keywords Realtionship Check
#' @examples
#' \dontrun{
#' tableTwo(formula = INDFMPIR ~RIAGENDR+ DMDBORN + RIDAGEMN, table=tableName, Multi=T)
#' tableTwo(formula = RIAGENDR ~ INDFMPIR + DMDBORN + RIDAGEMN, table=tableName, Multi=F)
#' }
#' @export
tableTwo<-function(formula, table, Multi=TRUE, CI=TRUE, poisson=FALSE){
  digit=4

  #Get all the labels
  getlables <- function(x){
    allables<-NULL
    for(i in seq_along(x)){
      allables<-c(allables, sapply(x[i], attr, which = "label", exact = TRUE))
    }
    return(allables)
  }

  # add lables to table
  labelcol<-function(data, labe){
    name1<-names(data)
    name2<-names(labe)
    newlabels<-unname(labe)
    Hmisc::label(data) = as.list(newlabels[match(name1,name2)])
    return(data)
  }

  # drop missing value with label
  drop_allna<-function(data, troplist){
    labelnames<-getlables(data)
    if(length(troplist)<=1){
      data<-filter(data, !is.na(eval(parse(text = troplist[1]))))
    }else{
      for(i in seq_along(troplist)[-1]){
        data<-filter(data, !is.na(eval(parse(text = troplist[i]))))
      }
    }
    data<-labelcol(data, labelnames)
  }

  #change value lables under different condition
  changename<-function(allxtext, Values){
    for(i in seq_along(allxtext)){
      xtext <- allxtext[i]
      xvalue <- table[xtext][[1]]
      xlable<-unname(getlables(table[xtext]))
      xtypes <- class(xvalue)
      xypenul <- ifelse((length(xtypes) >= 1), tail(xtypes, n = 1), xtypes)

      for(j in seq_along(Values)){
        if(str_detect(Values[j], xtext)){
          if(xypenul=="factor"){
            Values[j] <- gsub(allxtext[i], paste0(allxtext[i],": "), Values[j])
          }else{
            Values[j] <- gsub(allxtext[i], paste0(allxtext[i],": ", xlable), Values[j])
          }
        }
      }
    }
    return(Values)
  }

  vars<-all.vars(formula)
  ytext<-all.vars(formula[[2]])
  table<-drop_allna(table, ytext)
  yvalue<-table[ytext][[1]]
  ylable<-unname(getlables(table[ytext]))
  allxtext<-all.vars(formula[[3]])
  types<-class(yvalue)
  typenul<-ifelse((length(types)>=1), tail(types, n=1), types)

  if(typenul=="factor"){
    if(length(unique(yvalue))==2){
      if(Multi==TRUE){

        table<-drop_allna(table, allxtext)
        if(nrow(table)==0) stop("Too many missing values.")

        logit_step = glm(formula, data = table, family = "binomial")
        Table<-data.frame(Estimate=round(coef(logit_step),4), OR=exp(coef(logit_step)),
                          round(exp(confint(logit_step)), 3),summary(logit_step)$coefficients[,4])
        Table <- Table[-1,]
      }else{
        OR<- lapply(allxtext, function(var) {
          formu <- as.formula(paste(ytext, "~", var))
          res.logist <- glm(formu, data = table, family = "binomial")
          ORT<-data.frame(round(summary(res.logist)$coefficients[,1],3),
                          round(exp(cbind(OR = coef(res.logist), confint(res.logist))), 3),
                          summary(res.logist)$coefficients[,4])
          ORT[-1,]
        })
        Table<-do.call(rbind.data.frame, OR)
      }

      Table <- unname(Table)
      colnames(Table) <- c("Coefficient", "OR Ratio", "CI_25", "CI_75%", "p-value")
      Values <- rownames(Table)
      Values <- changename(allxtext, Values)
      Table <- data.frame(Values, Table)
      rownames(Table) <- NULL

      if(CI == FALSE){
        Table <- Table[, -c(4,5)]
      }

      graphTable <- unname(Table)
      boxOdds = unlist(list(graphTable[3]))
      names(boxOdds) <- Values
      boxCILow = unlist(list(graphTable[4]))
      names(boxCILow) <- Values
      boxCIHigh = unlist(list(graphTable[5]))
      names(boxCIHigh) <- Values

      df <- data.frame(yAxis = length(Values):1, boxOdds, boxCILow, boxCIHigh)
      p <- ggplot(df, aes(x = boxOdds, y = Values)) +
        geom_vline(aes(xintercept = 1), size = .25, linetype = "dashed") +
        geom_errorbarh(aes(xmax = boxCIHigh, xmin = boxCILow), size = .5, height =.2, color = "gray50") +
        geom_point(size = 3.5, color = "orange") +  theme_bw() + xlab("Log Odds ratio") +  ggtitle(ylable)+
        theme(panel.grid.minor = element_blank())
      return(list(Table, p))
    }else{
      stop("Sorry this formula cannot work. The categorical respones variables has to be less than three levels.")
    }
  }else{
    Table <- data.frame(Variable = character(), p.value = numeric(), CI_25 = numeric(),
                        CI_75 = numeric(), Method = character(), stringsAsFactors = F)
    track<-1
    for(i in seq_along(allxtext)){
      xtext <- allxtext[i]
      xvalue <- table[xtext][[1]]
      xlable<-unname(getlables(table[xtext]))

      #combine to table
      df <- data.frame(yvalue, xvalue)
      colnames(df)<-c(ytext, xtext)
      df <- drop_allna(df, xtext) # drop all NA

      #check if x is factor or numeric
      xtypes <- class(xvalue)
      xypenul <- ifelse((length(xtypes) >= 1), tail(xtypes, n = 1), xtypes)

      formula <- as.formula(paste(names(df)[1], "~", names(df)[2]))

      if (nrow(df) > 4) {
        if (xypenul == 'factor'){
          if (length(unique(df[[2]])) == 2){
            if (nrow(df) > 3 & nrow(df) < 5000){
              if (shapiro.test(unlist(df[[1]]))$p.value > 0.1){
                result <- t.test(formula, data = df)
                Table[track,1] <- paste0(xtext,": ",xlable)
                Table[track,2] <- round(result$p.value,digit)
                Table[track,3] <- round(result$conf.int[1],digit)
                Table[track,4] <- round(result$conf.int[2],digit)
                Table[track,5] <-"T-Test"
                track<-track+1
              }else{
                result <- wilcox.test(formula, data = df, conf.int = T)
                Table[track,1] <- paste0(xtext,": ",xlable)
                Table[track,2] <- round(result$p.value,digit)
                Table[track,3] <- round(result$conf.int[1],digit)
                Table[track,4] <- round(result$conf.int[2],digit)
                Table[track,5] <-"Wilcoxon test"
                track<-track+1
              }
            }else{
              result <- t.test(formula, data = df)
              Table[track,1] <- paste0(xtext,": ",xlable)
              Table[track,2] <- round(result$p.value,digit)
              Table[track,3] <- round(result$conf.int[1],digit)
              Table[track,4] <- round(result$conf.int[2],digit)
              Table[track,5] <-"T-Test"
              track<-track+1
            }
          }else{
            if (nrow(df) > 3 & nrow(df) < 5000){
              if (shapiro.test(unlist(df[[1]]))$p.value > 0.1){
                p <- anova(lm(formula, data = df))$`Pr(>F)`[1]
                #coef <- anova(lm(formula, data = df))$coef
                Table[track,1] <- paste0(xtext,": ",xlable)
                Table[track,2] <- round(p,digit)
                Table[track,3] <- "-"
                Table[track,4] <- "-"
                Table[track,5] <-"ANOVA"
                track<-track+1

              }else{
                p <- kruskal.test(formula, data = df)$p.value
                #coef <- kruskal.test(formula, data = df)$coef
                Table[track,1] <- paste0(xtext,": ",xlable)
                Table[track,2] <- round(p,digit)
                Table[track,3] <- "-"
                Table[track,4] <- "-"
                Table[track,5] <-"Kruskal-Wallis Test"
                track<-track+1
              }
            }else{
              p <- anova(lm(formula, data = df))$`Pr(>F)`[1]
              #coef <- anova(lm(formula, data = df))$coef
              Table[track,1] <- paste0(xtext,": ",xlable)
              Table[track,2] <- round(p,digit)
              Table[track,3] <- "-"
              Table[track,4] <- "-"
              Table[track,5] <-"ANOVA"
              track<-track+1
            }
          }
        }else{
          if (poisson == TRUE){
            glmresult <- glm(formula, data = df, family = poisson(link = 'log'))
            summaryglm <- summary(glmresult)$coefficients
            Table[track,1] <- paste0(xtext,": ",xlable)
            Table[track,2] <- round(summaryglm[4],digit)
            Table[track,3] <- "-"
            Table[track,4] <- "-"
            Table[track,5] <-"General Linear Model"
            track<-track+1
          }else{
            lmresult <- lm(formula, data = df)
            summarylm <- summary(lmresult)$coefficients
            #coef <- lm(lm(formula, data = df))$coef
            Table[track,1] <- paste0(xtext,": ",xlable)
            Table[track,2] <- round(summarylm[4],digit)
            Table[track,3] <- "-"
            Table[track,4] <- "-"
            Table[track,5] <-"Linear Model"
            track<-track+1
          }
        }
      }else {

      }
    }
    return(Table)
  }
}
